namespace TigerCS.Web.Models;

/// <summary>
/// In-memory mock data for the pilot UI screens. Replace with real API/DB
/// calls once the Tickets module backend is available (MVP-API-Contracts.md).
/// </summary>
public static class TicketMockRepository
{
    public static IReadOnlyList<TicketRecord> TodaysTickets { get; } = BuildTodaysTickets();

    public static IReadOnlyList<TicketRecord> PendingTickets { get; } = BuildPendingTickets();

    public static TicketRecord? GetById(string id)
    {
        return TodaysTickets.Concat(PendingTickets)
            .FirstOrDefault(t => string.Equals(t.Id, id, StringComparison.OrdinalIgnoreCase));
    }

    private static List<TicketRecord> BuildTodaysTickets()
    {
        return
        [
            new TicketRecord(
                Id: "TKT-2026-01842",
                Subject: "Water leakage reported in master bathroom",
                CustomerName: "Ahmed Khalil",
                Unit: "A-1204",
                Project: "Tiger Sky Tower",
                Priority: TicketPriority.Critical,
                Status: TicketStatus.Open,
                Department: "Maintenance",
                Owner: "Omar Nasser",
                Sla: SlaState.Breached,
                SlaText: "Breached by 42 min",
                LastActivity: "6 min ago",
                Source: "Genesys Call",
                CreatedDate: "Aug 24, 2026 · 08:12",
                CreatedBy: "Genesys IVR (Auto-logged)",
                Category: "Maintenance",
                Subcategory: "Plumbing",
                EscalationLevel: 2,
                CrmCustomerId: "CRM-77341",
                Mobile: "+971 50 214 7788",
                Email: "ahmed.khalil@example.com",
                PreferredLanguage: "English",
                Tower: "Tower A",
                UnitStatus: "Occupied — Owner",
                FirstResponseDue: "Aug 24, 2026 · 08:42",
                ResolutionDue: "Aug 24, 2026 · 12:12",
                RemainingOrBreach: "Breached by 42 min",
                Activities:
                [
                    new TicketActivity("created", "Genesys IVR", "Ticket created from inbound Genesys call", "Aug 24, 08:12"),
                    new TicketActivity("verified", "System", "Customer identity verified through CRM", "Aug 24, 08:14", "Matched CRM-77341 · Ahmed Khalil"),
                    new TicketActivity("assigned", "Sara Haddad", "Ticket assigned to Omar Nasser", "Aug 24, 08:19"),
                    new TicketActivity("priority", "Sara Haddad", "Priority changed from High to Critical", "Aug 24, 08:26", "Active leak confirmed, risk of damage to unit below"),
                    new TicketActivity("note", "Omar Nasser", "Internal note added", "Aug 24, 09:03", "Contacted building maintenance, technician dispatched to A-1204."),
                    new TicketActivity("reply", "Ahmed Khalil", "Customer reply received", "Aug 24, 09:41", "Leak has gotten worse, water is now reaching the hallway. Please send someone urgently.", HasAttachment: true),
                    new TicketActivity("sla", "System", "SLA breached", "Aug 24, 12:12", "Resolution SLA exceeded — escalation level raised to 2"),
                    new TicketActivity("transfer", "Omar Nasser", "Ticket transferred to Maintenance", "Aug 24, 12:18", "Escalated to on-site maintenance team for emergency plumbing response."),
                ]),
            new TicketRecord(
                Id: "TKT-2026-01839",
                Subject: "AC unit not cooling in living room",
                CustomerName: "Noura Al Farsi",
                Unit: "B-0805",
                Project: "Tiger Business Bay Residences",
                Priority: TicketPriority.High,
                Status: TicketStatus.InProgress,
                Department: "Maintenance",
                Owner: "Khalid Musa",
                Sla: SlaState.DueSoon,
                SlaText: "Due in 1h 10m",
                LastActivity: "18 min ago",
                Source: "Mobile App",
                CreatedDate: "Aug 24, 2026 · 07:05",
                CreatedBy: "Noura Al Farsi (Self-service)",
                Category: "Maintenance",
                Subcategory: "HVAC",
                EscalationLevel: 1,
                CrmCustomerId: "CRM-65210",
                Mobile: "+971 55 902 3341",
                Email: "noura.alfarsi@example.com",
                PreferredLanguage: "Arabic",
                Tower: "Tower B",
                UnitStatus: "Occupied — Tenant",
                FirstResponseDue: "Aug 24, 2026 · 07:35",
                ResolutionDue: "Aug 24, 2026 · 11:05",
                RemainingOrBreach: "Due in 1h 10m",
                Activities: GenericActivities("Noura Al Farsi", "Khalid Musa", "AC unit not cooling in living room", "Aug 24")),
            new TicketRecord(
                Id: "TKT-2026-01837",
                Subject: "Request for parking access card replacement",
                CustomerName: "Rami Sayegh",
                Unit: "C-1502",
                Project: "Tiger Sky Tower",
                Priority: TicketPriority.Low,
                Status: TicketStatus.Open,
                Department: "Facilities",
                Owner: "Maya Aoun",
                Sla: SlaState.OnTrack,
                SlaText: "Due in 5h 40m",
                LastActivity: "42 min ago",
                Source: "Email",
                CreatedDate: "Aug 24, 2026 · 06:50",
                CreatedBy: "Rami Sayegh",
                Category: "Facilities",
                Subcategory: "Access Control",
                EscalationLevel: 0,
                CrmCustomerId: "CRM-58122",
                Mobile: "+971 52 118 6604",
                Email: "rami.sayegh@example.com",
                PreferredLanguage: "English",
                Tower: "Tower C",
                UnitStatus: "Occupied — Owner",
                FirstResponseDue: "Aug 24, 2026 · 07:50",
                ResolutionDue: "Aug 24, 2026 · 12:30",
                RemainingOrBreach: "Due in 5h 40m",
                Activities: GenericActivities("Rami Sayegh", "Maya Aoun", "Request for parking access card replacement", "Aug 24")),
            new TicketRecord(
                Id: "TKT-2026-01831",
                Subject: "Billing discrepancy on service charge invoice",
                CustomerName: "Dana Qureshi",
                Unit: "A-0912",
                Project: "Tiger Business Bay Residences",
                Priority: TicketPriority.Medium,
                Status: TicketStatus.AwaitingCustomer,
                Department: "Finance",
                Owner: "Fadi Rahal",
                Sla: SlaState.OnTrack,
                SlaText: "Due in 1d 2h",
                LastActivity: "1h ago",
                Source: "Web Portal",
                CreatedDate: "Aug 23, 2026 · 15:22",
                CreatedBy: "Dana Qureshi (Self-service)",
                Category: "Billing",
                Subcategory: "Service Charges",
                EscalationLevel: 0,
                CrmCustomerId: "CRM-49087",
                Mobile: "+971 56 774 2190",
                Email: "dana.qureshi@example.com",
                PreferredLanguage: "English",
                Tower: "Tower A",
                UnitStatus: "Occupied — Owner",
                FirstResponseDue: "Aug 23, 2026 · 16:22",
                ResolutionDue: "Aug 25, 2026 · 15:22",
                RemainingOrBreach: "Due in 1d 2h",
                Activities: GenericActivities("Dana Qureshi", "Fadi Rahal", "Billing discrepancy on service charge invoice", "Aug 23")),
            new TicketRecord(
                Id: "TKT-2026-01828",
                Subject: "Elevator making unusual noise on floor 14",
                CustomerName: "Yousef Matar",
                Unit: "Common Area",
                Project: "Tiger Sky Tower",
                Priority: TicketPriority.High,
                Status: TicketStatus.Open,
                Department: "Maintenance",
                Owner: "Omar Nasser",
                Sla: SlaState.DueSoon,
                SlaText: "Due in 38m",
                LastActivity: "9 min ago",
                Source: "Phone",
                CreatedDate: "Aug 24, 2026 · 08:55",
                CreatedBy: "Yousef Matar",
                Category: "Maintenance",
                Subcategory: "Elevators",
                EscalationLevel: 1,
                CrmCustomerId: "CRM-71005",
                Mobile: "+971 50 663 8817",
                Email: "yousef.matar@example.com",
                PreferredLanguage: "English",
                Tower: "Tower A",
                UnitStatus: "Occupied — Tenant",
                FirstResponseDue: "Aug 24, 2026 · 09:25",
                ResolutionDue: "Aug 24, 2026 · 12:55",
                RemainingOrBreach: "Due in 38m",
                Activities: GenericActivities("Yousef Matar", "Omar Nasser", "Elevator making unusual noise on floor 14", "Aug 24")),
            new TicketRecord(
                Id: "TKT-2026-01822",
                Subject: "Request to update mailing address on file",
                CustomerName: "Hind Al Zaabi",
                Unit: "B-0311",
                Project: "Tiger Business Bay Residences",
                Priority: TicketPriority.Low,
                Status: TicketStatus.Closed,
                Department: "Customer Care",
                Owner: "Lina Youssef",
                Sla: SlaState.OnTrack,
                SlaText: "Met",
                LastActivity: "2h ago",
                Source: "Email",
                CreatedDate: "Aug 23, 2026 · 10:10",
                CreatedBy: "Hind Al Zaabi",
                Category: "Account",
                Subcategory: "Profile Update",
                EscalationLevel: 0,
                CrmCustomerId: "CRM-33847",
                Mobile: "+971 54 220 9915",
                Email: "hind.alzaabi@example.com",
                PreferredLanguage: "Arabic",
                Tower: "Tower B",
                UnitStatus: "Occupied — Owner",
                FirstResponseDue: "Aug 23, 2026 · 11:10",
                ResolutionDue: "Aug 24, 2026 · 10:10",
                RemainingOrBreach: "Closed on time",
                Activities: GenericActivities("Hind Al Zaabi", "Lina Youssef", "Request to update mailing address on file", "Aug 23")),
            new TicketRecord(
                Id: "TKT-2026-01819",
                Subject: "Noise complaint from neighboring unit",
                CustomerName: "Karim Debbas",
                Unit: "C-0718",
                Project: "Tiger Sky Tower",
                Priority: TicketPriority.Medium,
                Status: TicketStatus.InProgress,
                Department: "Customer Care",
                Owner: "Sara Haddad",
                Sla: SlaState.OnTrack,
                SlaText: "Due in 3h 15m",
                LastActivity: "55 min ago",
                Source: "Mobile App",
                CreatedDate: "Aug 24, 2026 · 07:40",
                CreatedBy: "Karim Debbas (Self-service)",
                Category: "Community",
                Subcategory: "Noise Complaint",
                EscalationLevel: 0,
                CrmCustomerId: "CRM-60219",
                Mobile: "+971 52 447 3302",
                Email: "karim.debbas@example.com",
                PreferredLanguage: "English",
                Tower: "Tower C",
                UnitStatus: "Occupied — Owner",
                FirstResponseDue: "Aug 24, 2026 · 08:10",
                ResolutionDue: "Aug 24, 2026 · 10:55",
                RemainingOrBreach: "Due in 3h 15m",
                Activities: GenericActivities("Karim Debbas", "Sara Haddad", "Noise complaint from neighboring unit", "Aug 24")),
        ];
    }

    private static List<TicketRecord> BuildPendingTickets()
    {
        return
        [
            new TicketRecord(
                Id: "TKT-2026-01798",
                Subject: "Awaiting photos for damaged ceiling panel",
                CustomerName: "Salma Nader",
                Unit: "A-0604",
                Project: "Tiger Sky Tower",
                Priority: TicketPriority.Medium,
                Status: TicketStatus.AwaitingCustomer,
                Department: "Maintenance",
                Owner: "Omar Nasser",
                Sla: SlaState.DueSoon,
                SlaText: "Due in 4h 05m",
                LastActivity: "3h ago",
                Source: "Web Portal",
                CreatedDate: "Aug 22, 2026 · 13:12",
                CreatedBy: "Salma Nader (Self-service)",
                Category: "Maintenance",
                Subcategory: "Structural",
                EscalationLevel: 0,
                CrmCustomerId: "CRM-40218",
                Mobile: "+971 50 331 7742",
                Email: "salma.nader@example.com",
                PreferredLanguage: "English",
                Tower: "Tower A",
                UnitStatus: "Occupied — Owner",
                FirstResponseDue: "Aug 22, 2026 · 14:12",
                ResolutionDue: "Aug 25, 2026 · 13:12",
                RemainingOrBreach: "Due in 4h 05m",
                Activities: GenericActivities("Salma Nader", "Omar Nasser", "Awaiting photos for damaged ceiling panel", "Aug 22")),
            new TicketRecord(
                Id: "TKT-2026-01791",
                Subject: "Confirming preferred appointment time for AC service",
                CustomerName: "Yousef Matar",
                Unit: "A-1204",
                Project: "Tiger Sky Tower",
                Priority: TicketPriority.Low,
                Status: TicketStatus.AwaitingCustomer,
                Department: "Maintenance",
                Owner: "Khalid Musa",
                Sla: SlaState.OnTrack,
                SlaText: "Due in 1d 6h",
                LastActivity: "5h ago",
                Source: "Phone",
                CreatedDate: "Aug 21, 2026 · 09:48",
                CreatedBy: "Yousef Matar",
                Category: "Maintenance",
                Subcategory: "HVAC",
                EscalationLevel: 0,
                CrmCustomerId: "CRM-71005",
                Mobile: "+971 50 663 8817",
                Email: "yousef.matar@example.com",
                PreferredLanguage: "English",
                Tower: "Tower A",
                UnitStatus: "Occupied — Tenant",
                FirstResponseDue: "Aug 21, 2026 · 10:48",
                ResolutionDue: "Aug 26, 2026 · 09:48",
                RemainingOrBreach: "Due in 1d 6h",
                Activities: GenericActivities("Yousef Matar", "Khalid Musa", "Confirming preferred appointment time for AC service", "Aug 21")),
            new TicketRecord(
                Id: "TKT-2026-01784",
                Subject: "Pending customer confirmation on refund amount",
                CustomerName: "Dana Qureshi",
                Unit: "A-0912",
                Project: "Tiger Business Bay Residences",
                Priority: TicketPriority.Medium,
                Status: TicketStatus.AwaitingCustomer,
                Department: "Finance",
                Owner: "Fadi Rahal",
                Sla: SlaState.OnTrack,
                SlaText: "Due in 2d 1h",
                LastActivity: "1d ago",
                Source: "Web Portal",
                CreatedDate: "Aug 20, 2026 · 11:30",
                CreatedBy: "Dana Qureshi (Self-service)",
                Category: "Billing",
                Subcategory: "Refund",
                EscalationLevel: 0,
                CrmCustomerId: "CRM-49087",
                Mobile: "+971 56 774 2190",
                Email: "dana.qureshi@example.com",
                PreferredLanguage: "English",
                Tower: "Tower A",
                UnitStatus: "Occupied — Owner",
                FirstResponseDue: "Aug 20, 2026 · 12:30",
                ResolutionDue: "Aug 27, 2026 · 11:30",
                RemainingOrBreach: "Due in 2d 1h",
                Activities: GenericActivities("Dana Qureshi", "Fadi Rahal", "Pending customer confirmation on refund amount", "Aug 20")),
            new TicketRecord(
                Id: "TKT-2026-01776",
                Subject: "Awaiting access approval from building security",
                CustomerName: "Hind Al Zaabi",
                Unit: "B-0311",
                Project: "Tiger Business Bay Residences",
                Priority: TicketPriority.Low,
                Status: TicketStatus.AwaitingCustomer,
                Department: "Facilities",
                Owner: "Maya Aoun",
                Sla: SlaState.OnTrack,
                SlaText: "Due in 3d",
                LastActivity: "1d ago",
                Source: "Email",
                CreatedDate: "Aug 19, 2026 · 16:05",
                CreatedBy: "Hind Al Zaabi",
                Category: "Facilities",
                Subcategory: "Access Control",
                EscalationLevel: 0,
                CrmCustomerId: "CRM-33847",
                Mobile: "+971 54 220 9915",
                Email: "hind.alzaabi@example.com",
                PreferredLanguage: "Arabic",
                Tower: "Tower B",
                UnitStatus: "Occupied — Owner",
                FirstResponseDue: "Aug 19, 2026 · 17:05",
                ResolutionDue: "Aug 26, 2026 · 16:05",
                RemainingOrBreach: "Due in 3d",
                Activities: GenericActivities("Hind Al Zaabi", "Maya Aoun", "Awaiting access approval from building security", "Aug 19")),
            new TicketRecord(
                Id: "TKT-2026-01768",
                Subject: "Waiting on customer to reschedule maintenance visit",
                CustomerName: "Karim Debbas",
                Unit: "C-0718",
                Project: "Tiger Sky Tower",
                Priority: TicketPriority.Medium,
                Status: TicketStatus.AwaitingCustomer,
                Department: "Maintenance",
                Owner: "Sara Haddad",
                Sla: SlaState.DueSoon,
                SlaText: "Due in 9h 20m",
                LastActivity: "2d ago",
                Source: "Mobile App",
                CreatedDate: "Aug 18, 2026 · 09:00",
                CreatedBy: "Karim Debbas (Self-service)",
                Category: "Maintenance",
                Subcategory: "Scheduling",
                EscalationLevel: 0,
                CrmCustomerId: "CRM-60219",
                Mobile: "+971 52 447 3302",
                Email: "karim.debbas@example.com",
                PreferredLanguage: "English",
                Tower: "Tower C",
                UnitStatus: "Occupied — Owner",
                FirstResponseDue: "Aug 18, 2026 · 10:00",
                ResolutionDue: "Aug 24, 2026 · 09:00",
                RemainingOrBreach: "Due in 9h 20m",
                Activities: GenericActivities("Karim Debbas", "Sara Haddad", "Waiting on customer to reschedule maintenance visit", "Aug 18")),
        ];
    }

    private static IReadOnlyList<TicketActivity> GenericActivities(string customer, string owner, string subject, string createdDay)
    {
        return
        [
            new TicketActivity("created", "Genesys IVR", "Ticket created from inbound Genesys call", $"{createdDay}, 09:02"),
            new TicketActivity("verified", "System", "Customer identity verified through CRM", $"{createdDay}, 09:04"),
            new TicketActivity("assigned", "Sara Haddad", $"Ticket assigned to {owner}", $"{createdDay}, 09:11"),
            new TicketActivity("note", owner, "Internal note added", $"{createdDay}, 10:20", $"Reviewing \"{subject}\" and coordinating next steps."),
            new TicketActivity("reply", customer, "Customer reply received", $"{createdDay}, 11:05", "Thank you, please keep me posted on the update."),
        ];
    }
}
