// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TigerCS.Infrastructure.Persistence;

#nullable disable

namespace TigerCS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TigerCsDbContext))]
    [Migration("20260904075902_AddWorkflowAutomation")]
    partial class AddWorkflowAutomation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TigerCS.Domain.Audit.AuditEntry", b =>
                {
                    b.Property<long>("AuditEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditEntryId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ActorEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AfterValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeforeValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("AuditEntryId");

                    b.ToTable("AuditEntries", (string)null);
                });

            modelBuilder.Entity("TigerCS.Domain.Infrastructure.IdempotencyRecord", b =>
                {
                    b.Property<long>("IdempotencyRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdempotencyRecordId"));

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FirstSeenAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResultReference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdempotencyRecordId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_IdempotencyRecords_IdempotencyKey");

                    b.ToTable("IdempotencyRecords", (string)null);
                });

            modelBuilder.Entity("TigerCS.Domain.Infrastructure.OutboxMessage", b =>
                {
                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("IdempotencyRecordId")
                        .HasColumnType("bigint");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("OutboxMessageId");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_OutboxMessages_CorrelationId");

                    b.HasIndex("IdempotencyRecordId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_OutboxMessages_DeadLettered")
                        .HasFilter("[Status] = 3");

                    b.HasIndex("Status", "OccurredAtUtc")
                        .HasDatabaseName("IX_OutboxMessages_Status_OccurredAtUtc")
                        .HasFilter("[Status] = 1");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.ClassificationAndRouting.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.CustomerVerification.ContactReference", b =>
                {
                    b.Property<int>("ContactReferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactReferenceId"));

                    b.Property<int?>("AuthorizedRepresentativeOfContactReferenceId")
                        .HasColumnType("int");

                    b.Property<string>("ContactChannel")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ContactType")
                        .HasColumnType("int");

                    b.Property<string>("CrmContactId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UnitReferenceId")
                        .HasColumnType("int");

                    b.HasKey("ContactReferenceId");

                    b.HasIndex("AuthorizedRepresentativeOfContactReferenceId");

                    b.HasIndex("CrmContactId")
                        .IsUnique();

                    b.HasIndex("UnitReferenceId");

                    b.ToTable("ContactReferences", (string)null);
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.CustomerVerification.UnitReference", b =>
                {
                    b.Property<int>("UnitReferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitReferenceId"));

                    b.Property<string>("CrmUnitId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PropertyName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TowerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UnitType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UnitReferenceId");

                    b.HasIndex("CrmUnitId")
                        .IsUnique();

                    b.ToTable("UnitReferences", (string)null);
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.CustomerVerification.VerificationSession", b =>
                {
                    b.Property<Guid>("VerificationSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ConfirmedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ConsumedByTicketId")
                        .HasColumnType("bigint");

                    b.Property<int>("ContactReferenceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("SnapshotContactChannel")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SnapshotContactDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SnapshotPropertyName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SnapshotTowerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SnapshotUnitNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SnapshotUnitType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<int>("UnitReferenceId")
                        .HasColumnType("int");

                    b.Property<int?>("VerificationMethod")
                        .HasColumnType("int");

                    b.HasKey("VerificationSessionId");

                    b.HasIndex("ContactReferenceId");

                    b.HasIndex("UnitReferenceId");

                    b.HasIndex("AgentEmployeeId", "IdempotencyKey")
                        .IsUnique()
                        .HasFilter("[IdempotencyKey] IS NOT NULL");

                    b.ToTable("VerificationSessions", (string)null);
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.IdentityAndAccess.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DepartmentId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.IdentityAndAccess.Employee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeactivatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsGeynessStaff")
                        .HasColumnType("bit");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.IdentityAndAccess.UserDepartmentAssignment", b =>
                {
                    b.Property<int>("UserDepartmentAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserDepartmentAssignmentId"));

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("AssignedByEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.HasKey("UserDepartmentAssignmentId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserDepartmentAssignments_EmployeeId_PrimaryOnly")
                        .HasFilter("[IsPrimary] = 1");

                    b.HasIndex("EmployeeId", "DepartmentId")
                        .IsUnique();

                    b.ToTable("UserDepartmentAssignments", (string)null);
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.Notifications.Notification", b =>
                {
                    b.Property<long>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NotificationId"));

                    b.Property<byte>("Channel")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte>("DeliveryStatus")
                        .HasColumnType("tinyint");

                    b.Property<byte>("NotificationType")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("OutboxMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RecipientAddress")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<Guid?>("RecipientEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<long?>("TicketId")
                        .HasColumnType("bigint");

                    b.HasKey("NotificationId");

                    b.HasIndex("DeliveryStatus")
                        .HasDatabaseName("IX_Notifications_DeliveryStatus");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("IX_Notifications_TicketId");

                    b.HasIndex("OutboxMessageId", "NotificationType")
                        .IsUnique()
                        .HasDatabaseName("UX_Notifications_OutboxMessageId_NotificationType")
                        .HasFilter("[OutboxMessageId] IS NOT NULL");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.SlaAndEscalation.BusinessCalendar", b =>
                {
                    b.Property<int>("BusinessCalendarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BusinessCalendarId"));

                    b.Property<TimeOnly>("BusinessDayEndLocal")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("BusinessDayStartLocal")
                        .HasColumnType("time");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BusinessCalendarId");

                    b.ToTable("BusinessCalendars", null, t =>
                        {
                            t.HasCheckConstraint("CK_BusinessCalendars_WindowOrder", "[BusinessDayEndLocal] > [BusinessDayStartLocal]");
                        });
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.SlaAndEscalation.BusinessCalendarWorkingDay", b =>
                {
                    b.Property<int>("BusinessCalendarWorkingDayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BusinessCalendarWorkingDayId"));

                    b.Property<int>("BusinessCalendarId")
                        .HasColumnType("int");

                    b.Property<byte>("DayOfWeek")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsWorkingDay")
                        .HasColumnType("bit");

                    b.HasKey("BusinessCalendarWorkingDayId");

                    b.HasIndex("BusinessCalendarId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("BusinessCalendarWorkingDays", null, t =>
                        {
                            t.HasCheckConstraint("CK_BusinessCalendarWorkingDays_DayOfWeekRange", "[DayOfWeek] BETWEEN 0 AND 6");
                        });
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.SlaAndEscalation.Holiday", b =>
                {
                    b.Property<int>("HolidayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HolidayId"));

                    b.Property<int>("BusinessCalendarId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ConfirmedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ConfirmedByEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("EnteredByEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("HolidayDate")
                        .HasColumnType("date");

                    b.HasKey("HolidayId");

                    b.HasIndex("ConfirmedByEmployeeId");

                    b.HasIndex("EnteredByEmployeeId");

                    b.HasIndex("BusinessCalendarId", "HolidayDate")
                        .IsUnique();

                    b.ToTable("Holidays", (string)null);
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.SlaAndEscalation.Priority", b =>
                {
                    b.Property<byte>("PriorityId")
                        .HasColumnType("tinyint");

                    b.Property<byte>("DisplayOrder")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PriorityId");

                    b.ToTable("Priorities", (string)null);
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.SlaAndEscalation.SlaPolicy", b =>
                {
                    b.Property<byte>("PriorityId")
                        .HasColumnType("tinyint");

                    b.Property<byte>("ClockBasis")
                        .HasColumnType("tinyint");

                    b.Property<int>("FirstResponseTargetMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte>("Level2ToGmWindowUnit")
                        .HasColumnType("tinyint");

                    b.Property<int>("Level2ToGmWindowValue")
                        .HasColumnType("int");

                    b.Property<int>("ResolutionTargetMinutes")
                        .HasColumnType("int");

                    b.Property<decimal>("WarningThresholdPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("PriorityId");

                    b.ToTable("SlaPolicies", null, t =>
                        {
                            t.HasCheckConstraint("CK_SlaPolicies_PositiveTargets", "[FirstResponseTargetMinutes] > 0 AND [ResolutionTargetMinutes] > 0");
                        });
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.SlaAndEscalation.TicketEscalation", b =>
                {
                    b.Property<long>("TicketEscalationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TicketEscalationId"));

                    b.Property<byte>("Level")
                        .HasColumnType("tinyint");

                    b.Property<string>("NotifiedRoles")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("RaisedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RespondedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RespondingEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("TicketId")
                        .HasColumnType("bigint");

                    b.Property<byte>("TriggerType")
                        .HasColumnType("tinyint");

                    b.HasKey("TicketEscalationId");

                    b.HasIndex("RespondingEmployeeId");

                    b.HasIndex("TicketId")
                        .IsUnique()
                        .HasDatabaseName("UX_TicketEscalations_OneAutoBreachPerTicket")
                        .HasFilter("[TriggerType] = 1");

                    b.HasIndex("TicketId", "RaisedAtUtc")
                        .HasDatabaseName("IX_TicketEscalations_TicketRaisedAt");

                    b.ToTable("TicketEscalations", null, t =>
                        {
                            t.HasCheckConstraint("CK_TicketEscalations_Level4IsManualOnly", "([Level] = 4 AND [TriggerType] = 4) OR ([Level] <> 4 AND [TriggerType] <> 4)");

                            t.HasCheckConstraint("CK_TicketEscalations_LevelRange", "[Level] BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.SlaAndEscalation.TicketSlaInstance", b =>
                {
                    b.Property<long>("TicketSlaInstanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TicketSlaInstanceId"));

                    b.Property<Guid?>("ApprovedByEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("ChangeReason")
                        .HasColumnType("tinyint");

                    b.Property<bool>("FirstResponseBreached")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FirstResponseDueAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PeriodEndAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodStartAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte>("PriorityId")
                        .HasColumnType("tinyint");

                    b.Property<bool>("ResolutionBreached")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ResolutionDueAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("TicketId")
                        .HasColumnType("bigint");

                    b.HasKey("TicketSlaInstanceId");

                    b.HasIndex("ApprovedByEmployeeId");

                    b.HasIndex("PriorityId");

                    b.HasIndex("TicketId")
                        .IsUnique()
                        .HasDatabaseName("UX_TicketSlaInstances_CurrentPeriodPerTicket")
                        .HasFilter("[PeriodEndAtUtc] IS NULL");

                    b.HasIndex("PeriodEndAtUtc", "FirstResponseBreached", "FirstResponseDueAtUtc")
                        .HasDatabaseName("IX_TicketSlaInstances_FirstResponseSweep");

                    b.HasIndex("PeriodEndAtUtc", "ResolutionBreached", "ResolutionDueAtUtc")
                        .HasDatabaseName("IX_TicketSlaInstances_ResolutionSweep");

                    b.ToTable("TicketSlaInstances", null, t =>
                        {
                            t.HasCheckConstraint("CK_TicketSlaInstances_DowngradeRequiresApprover", "[ChangeReason] <> 3 OR [ApprovedByEmployeeId] IS NOT NULL");

                            t.HasCheckConstraint("CK_TicketSlaInstances_PeriodOrder", "[PeriodEndAtUtc] IS NULL OR [PeriodEndAtUtc] >= [PeriodStartAtUtc]");
                        });
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.Ticketing.DepartmentCustomerLookupSource", b =>
                {
                    b.Property<int>("DepartmentCustomerLookupSourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentCustomerLookupSourceId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<byte>("Source")
                        .HasColumnType("tinyint");

                    b.HasKey("DepartmentCustomerLookupSourceId");

                    b.HasIndex("DepartmentId", "Source")
                        .IsUnique();

                    b.ToTable("DepartmentCustomerLookupSources", (string)null);
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.Ticketing.IntakeRecord", b =>
                {
                    b.Property<long>("IntakeRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IntakeRecordId"));

                    b.Property<byte>("ChannelId")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("CreatedByEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("CrmVerificationStatus")
                        .HasColumnType("tinyint");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsUnitRelated")
                        .HasColumnType("bit");

                    b.Property<long?>("LinkedTicketId")
                        .HasColumnType("bigint");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte?>("PriorityHint")
                        .HasColumnType("tinyint");

                    b.Property<string>("RawUnitNumberEntered")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("IntakeRecordId");

                    b.HasIndex("CreatedByEmployeeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("LinkedTicketId");

                    b.HasIndex("PriorityHint");

                    b.ToTable("IntakeRecords", (string)null);
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.Ticketing.Ticket", b =>
                {
                    b.Property<long>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TicketId"));

                    b.Property<DateTime?>("AcknowledgementSentAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("ContactReferenceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CrmBuyerCustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CrmBuyerCustomerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("CrmBuyerLeadId")
                        .HasColumnType("int");

                    b.Property<int?>("CrmBuyerProjectId")
                        .HasColumnType("int");

                    b.Property<string>("CrmBuyerProjectName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("CrmBuyerUnitId")
                        .HasColumnType("int");

                    b.Property<string>("CrmBuyerUnitNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CurrentDepartmentId")
                        .HasColumnType("int");

                    b.Property<Guid?>("CurrentOwnerEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerVerificationSource")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long?>("DuplicateOfTicketId")
                        .HasColumnType("bigint");

                    b.Property<byte>("EscalationLevel")
                        .HasColumnType("tinyint");

                    b.Property<string>("ExternalCustomerId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ExternalUnitId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("FirstHumanResponseAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ManualProjectName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ManualUnitNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OriginatingDepartmentId")
                        .HasColumnType("int");

                    b.Property<byte>("PriorityId")
                        .HasColumnType("tinyint");

                    b.Property<int>("ReopenCount")
                        .HasColumnType("int");

                    b.Property<string>("RequestSummary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("RequestTypeId")
                        .HasColumnType("int");

                    b.Property<byte?>("ResolutionOutcome")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("SlaState")
                        .HasColumnType("tinyint");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<byte>("TicketStatus")
                        .HasColumnType("tinyint");

                    b.Property<int?>("UnitReferenceId")
                        .HasColumnType("int");

                    b.Property<byte>("VerificationStatus")
                        .HasColumnType("tinyint");

                    b.HasKey("TicketId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ContactReferenceId");

                    b.HasIndex("CurrentDepartmentId");

                    b.HasIndex("CurrentOwnerEmployeeId");

                    b.HasIndex("DuplicateOfTicketId");

                    b.HasIndex("OriginatingDepartmentId");

                    b.HasIndex("PriorityId");

                    b.HasIndex("RequestTypeId");

                    b.HasIndex("TicketNumber")
                        .IsUnique();

                    b.HasIndex("UnitReferenceId");

                    b.HasIndex("CustomerVerificationSource", "ExternalCustomerId")
                        .HasFilter("[ExternalCustomerId] IS NOT NULL");

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.Ticketing.TicketAssignment", b =>
                {
                    b.Property<long>("TicketAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TicketAssignmentId"));

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("AssignedDepartmentId")
                        .HasColumnType("int");

                    b.Property<Guid>("AssignedEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssigningActorEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<long>("TicketId")
                        .HasColumnType("bigint");

                    b.HasKey("TicketAssignmentId");

                    b.HasIndex("AssignedDepartmentId");

                    b.HasIndex("AssignedEmployeeId");

                    b.HasIndex("AssigningActorEmployeeId");

                    b.HasIndex("TicketId")
                        .IsUnique()
                        .HasFilter("[IsCurrent] = 1");

                    b.ToTable("TicketAssignments", (string)null);
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.Ticketing.TicketInteractionContext", b =>
                {
                    b.Property<long>("TicketId")
                        .HasColumnType("bigint");

                    b.Property<string>("CalledNumber")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<byte>("ChannelId")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Direction")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("GenesysAgentId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("GenesysAgentName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GenesysConversationId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("GenesysQueueId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("GenesysQueueName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("InteractionStartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Source")
                        .HasColumnType("tinyint");

                    b.HasKey("TicketId");

                    b.HasIndex("GenesysConversationId")
                        .HasFilter("[GenesysConversationId] IS NOT NULL");

                    b.ToTable("TicketInteractionContexts", (string)null);
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.Ticketing.TicketNote", b =>
                {
                    b.Property<long>("TicketNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TicketNoteId"));

                    b.Property<Guid>("AuthorEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long>("TicketId")
                        .HasColumnType("bigint");

                    b.HasKey("TicketNoteId");

                    b.HasIndex("AuthorEmployeeId");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketNotes", (string)null);
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.Ticketing.TicketPendingRecord", b =>
                {
                    b.Property<long>("TicketPendingRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TicketPendingRecordId"));

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Kind")
                        .HasColumnType("tinyint");

                    b.Property<byte>("PreviousStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ResumedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ResumedByEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StartedByEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("TicketId")
                        .HasColumnType("bigint");

                    b.HasKey("TicketPendingRecordId");

                    b.HasIndex("ResumedByEmployeeId");

                    b.HasIndex("StartedByEmployeeId");

                    b.HasIndex("TicketId")
                        .IsUnique()
                        .HasDatabaseName("UX_TicketPendingRecords_OpenPerTicket")
                        .HasFilter("[ResumedAtUtc] IS NULL");

                    b.ToTable("TicketPendingRecords", (string)null);
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.Ticketing.TicketRequesterSnapshot", b =>
                {
                    b.Property<long>("TicketId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SnapshotContactChannel")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SnapshotContactDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SnapshotPropertyName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SnapshotTowerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SnapshotUnitNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SnapshotUnitType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TicketId");

                    b.ToTable("TicketRequesterSnapshots", (string)null);
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.Ticketing.TicketResolution", b =>
                {
                    b.Property<long>("TicketResolutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TicketResolutionId"));

                    b.Property<long?>("DuplicateOfTicketId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<byte?>("ReasonCode")
                        .HasColumnType("tinyint");

                    b.Property<string>("ResolutionNote")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<byte>("ResolutionOutcome")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("ResolvedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ResolvingEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("TicketId")
                        .HasColumnType("bigint");

                    b.HasKey("TicketResolutionId");

                    b.HasIndex("DuplicateOfTicketId");

                    b.HasIndex("ResolvingEmployeeId");

                    b.HasIndex("TicketId")
                        .IsUnique()
                        .HasFilter("[IsCurrent] = 1");

                    b.ToTable("TicketResolutions", (string)null);
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.Ticketing.TicketStatusHistory", b =>
                {
                    b.Property<long>("TicketStatusHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TicketStatusHistoryId"));

                    b.Property<Guid?>("ActorEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ActorIsSystem")
                        .HasColumnType("bit");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Dimension")
                        .HasColumnType("tinyint");

                    b.Property<byte>("NewValue")
                        .HasColumnType("tinyint");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("OldValue")
                        .HasColumnType("tinyint");

                    b.Property<long>("TicketId")
                        .HasColumnType("bigint");

                    b.HasKey("TicketStatusHistoryId");

                    b.HasIndex("ActorEmployeeId");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketStatusHistory", (string)null);
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.WorkflowConfiguration.DepartmentWorkflowSettings", b =>
                {
                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("AllowAssignment")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowInternalReassignment")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowTransferToOtherDepartments")
                        .HasColumnType("bit");

                    b.Property<string>("HeadRoleName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SupervisorRoleName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("DepartmentId");

                    b.ToTable("DepartmentWorkflowSettings", (string)null);
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.WorkflowConfiguration.RequestType", b =>
                {
                    b.Property<int>("RequestTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestTypeId"));

                    b.Property<bool>("AllowAgentPriorityChange")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowPendingCustomer")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowPendingInternal")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowReopen")
                        .HasColumnType("bit");

                    b.Property<byte>("DefaultPriorityId")
                        .HasColumnType("tinyint");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequiredFieldsJson")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("WorkflowTemplateId")
                        .HasColumnType("int");

                    b.HasKey("RequestTypeId");

                    b.HasIndex("DefaultPriorityId");

                    b.HasIndex("WorkflowTemplateId");

                    b.HasIndex("DepartmentId", "Name")
                        .IsUnique();

                    b.ToTable("RequestTypes", (string)null);
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.WorkflowConfiguration.RequestTypeAssignmentRule", b =>
                {
                    b.Property<int>("RequestTypeAssignmentRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestTypeAssignmentRuleId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte>("Mode")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("PrimaryEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RequestTypeId")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RequestTypeAssignmentRuleId");

                    b.HasIndex("PrimaryEmployeeId");

                    b.HasIndex("RequestTypeId")
                        .IsUnique();

                    b.ToTable("RequestTypeAssignmentRules", (string)null);
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.WorkflowConfiguration.RequestTypeAssignmentRuleMember", b =>
                {
                    b.Property<int>("RequestTypeAssignmentRuleMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestTypeAssignmentRuleMemberId"));

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RequestTypeAssignmentRuleId")
                        .HasColumnType("int");

                    b.HasKey("RequestTypeAssignmentRuleMemberId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RequestTypeAssignmentRuleId", "EmployeeId")
                        .IsUnique();

                    b.ToTable("RequestTypeAssignmentRuleMembers", (string)null);
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.WorkflowConfiguration.RequestTypeSlaPolicy", b =>
                {
                    b.Property<int>("RequestTypeSlaPolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestTypeSlaPolicyId"));

                    b.Property<byte?>("ClockBasis")
                        .HasColumnType("tinyint");

                    b.Property<int?>("FirstResponseMaximumValue")
                        .HasColumnType("int");

                    b.Property<int?>("FirstResponseTargetValue")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsImmediate")
                        .HasColumnType("bit");

                    b.Property<bool?>("PausesOnPendingCustomer")
                        .HasColumnType("bit");

                    b.Property<bool?>("PausesOnPendingInternal")
                        .HasColumnType("bit");

                    b.Property<byte>("PriorityId")
                        .HasColumnType("tinyint");

                    b.Property<int>("RequestTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("ResolutionMaximumValue")
                        .HasColumnType("int");

                    b.Property<int?>("ResolutionTargetValue")
                        .HasColumnType("int");

                    b.Property<byte>("Trigger")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Unit")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("WarningThresholdPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("RequestTypeSlaPolicyId");

                    b.HasIndex("PriorityId");

                    b.HasIndex("RequestTypeId", "PriorityId")
                        .IsUnique();

                    b.ToTable("RequestTypeSlaPolicies", (string)null);
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.WorkflowConfiguration.WorkflowTemplate", b =>
                {
                    b.Property<int>("WorkflowTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkflowTemplateId"));

                    b.Property<bool>("AllowsPendingCustomer")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowsPendingInternal")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("bit");

                    b.HasKey("WorkflowTemplateId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("WorkflowTemplates", (string)null);
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.WorkflowConfiguration.WorkflowTemplateStep", b =>
                {
                    b.Property<int>("WorkflowTemplateStepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkflowTemplateStepId"));

                    b.Property<bool>("IsOptional")
                        .HasColumnType("bit");

                    b.Property<byte>("Kind")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("Sequence")
                        .HasColumnType("tinyint");

                    b.Property<int>("WorkflowTemplateId")
                        .HasColumnType("int");

                    b.HasKey("WorkflowTemplateStepId");

                    b.HasIndex("WorkflowTemplateId", "Sequence")
                        .IsUnique();

                    b.ToTable("WorkflowTemplateSteps", (string)null);
                });

            modelBuilder.Entity("TigerCS.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("TigerCS.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("TigerCS.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("TigerCS.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("TigerCS.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("TigerCS.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TigerCS.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("TigerCS.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TigerCS.Domain.Infrastructure.OutboxMessage", b =>
                {
                    b.HasOne("TigerCS.Domain.Infrastructure.IdempotencyRecord", "IdempotencyRecord")
                        .WithMany()
                        .HasForeignKey("IdempotencyRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdempotencyRecord");
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.ClassificationAndRouting.Category", b =>
                {
                    b.HasOne("TigerCS.Domain.Modules.IdentityAndAccess.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TigerCS.Domain.Modules.ClassificationAndRouting.Category", null)
                        .WithMany()
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.CustomerVerification.ContactReference", b =>
                {
                    b.HasOne("TigerCS.Domain.Modules.CustomerVerification.ContactReference", null)
                        .WithMany()
                        .HasForeignKey("AuthorizedRepresentativeOfContactReferenceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TigerCS.Domain.Modules.CustomerVerification.UnitReference", null)
                        .WithMany("Contacts")
                        .HasForeignKey("UnitReferenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.CustomerVerification.VerificationSession", b =>
                {
                    b.HasOne("TigerCS.Domain.Modules.CustomerVerification.ContactReference", null)
                        .WithMany()
                        .HasForeignKey("ContactReferenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TigerCS.Domain.Modules.CustomerVerification.UnitReference", null)
                        .WithMany()
                        .HasForeignKey("UnitReferenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.IdentityAndAccess.Employee", b =>
                {
                    b.HasOne("TigerCS.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("TigerCS.Domain.Modules.IdentityAndAccess.Employee", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.IdentityAndAccess.UserDepartmentAssignment", b =>
                {
                    b.HasOne("TigerCS.Domain.Modules.IdentityAndAccess.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TigerCS.Domain.Modules.IdentityAndAccess.Employee", "Employee")
                        .WithMany("DepartmentAssignments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.Notifications.Notification", b =>
                {
                    b.HasOne("TigerCS.Domain.Infrastructure.OutboxMessage", null)
                        .WithMany()
                        .HasForeignKey("OutboxMessageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TigerCS.Domain.Modules.Ticketing.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.SlaAndEscalation.BusinessCalendarWorkingDay", b =>
                {
                    b.HasOne("TigerCS.Domain.Modules.SlaAndEscalation.BusinessCalendar", null)
                        .WithMany()
                        .HasForeignKey("BusinessCalendarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.SlaAndEscalation.Holiday", b =>
                {
                    b.HasOne("TigerCS.Domain.Modules.SlaAndEscalation.BusinessCalendar", null)
                        .WithMany()
                        .HasForeignKey("BusinessCalendarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TigerCS.Domain.Modules.IdentityAndAccess.Employee", null)
                        .WithMany()
                        .HasForeignKey("ConfirmedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TigerCS.Domain.Modules.IdentityAndAccess.Employee", null)
                        .WithMany()
                        .HasForeignKey("EnteredByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.SlaAndEscalation.SlaPolicy", b =>
                {
                    b.HasOne("TigerCS.Domain.Modules.SlaAndEscalation.Priority", null)
                        .WithOne()
                        .HasForeignKey("TigerCS.Domain.Modules.SlaAndEscalation.SlaPolicy", "PriorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.SlaAndEscalation.TicketEscalation", b =>
                {
                    b.HasOne("TigerCS.Domain.Modules.IdentityAndAccess.Employee", null)
                        .WithMany()
                        .HasForeignKey("RespondingEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TigerCS.Domain.Modules.Ticketing.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.SlaAndEscalation.TicketSlaInstance", b =>
                {
                    b.HasOne("TigerCS.Domain.Modules.IdentityAndAccess.Employee", null)
                        .WithMany()
                        .HasForeignKey("ApprovedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TigerCS.Domain.Modules.SlaAndEscalation.Priority", null)
                        .WithMany()
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TigerCS.Domain.Modules.Ticketing.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.Ticketing.DepartmentCustomerLookupSource", b =>
                {
                    b.HasOne("TigerCS.Domain.Modules.IdentityAndAccess.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.Ticketing.IntakeRecord", b =>
                {
                    b.HasOne("TigerCS.Domain.Modules.IdentityAndAccess.Employee", null)
                        .WithMany()
                        .HasForeignKey("CreatedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TigerCS.Domain.Modules.IdentityAndAccess.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TigerCS.Domain.Modules.Ticketing.Ticket", null)
                        .WithMany()
                        .HasForeignKey("LinkedTicketId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TigerCS.Domain.Modules.SlaAndEscalation.Priority", null)
                        .WithMany()
                        .HasForeignKey("PriorityHint")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.Ticketing.Ticket", b =>
                {
                    b.HasOne("TigerCS.Domain.Modules.ClassificationAndRouting.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TigerCS.Domain.Modules.CustomerVerification.ContactReference", null)
                        .WithMany()
                        .HasForeignKey("ContactReferenceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TigerCS.Domain.Modules.IdentityAndAccess.Department", null)
                        .WithMany()
                        .HasForeignKey("CurrentDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TigerCS.Domain.Modules.IdentityAndAccess.Employee", null)
                        .WithMany()
                        .HasForeignKey("CurrentOwnerEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TigerCS.Domain.Modules.Ticketing.Ticket", null)
                        .WithMany()
                        .HasForeignKey("DuplicateOfTicketId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TigerCS.Domain.Modules.IdentityAndAccess.Department", null)
                        .WithMany()
                        .HasForeignKey("OriginatingDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TigerCS.Domain.Modules.SlaAndEscalation.Priority", null)
                        .WithMany()
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TigerCS.Domain.Modules.WorkflowConfiguration.RequestType", null)
                        .WithMany()
                        .HasForeignKey("RequestTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TigerCS.Domain.Modules.CustomerVerification.UnitReference", null)
                        .WithMany()
                        .HasForeignKey("UnitReferenceId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.Ticketing.TicketAssignment", b =>
                {
                    b.HasOne("TigerCS.Domain.Modules.IdentityAndAccess.Department", null)
                        .WithMany()
                        .HasForeignKey("AssignedDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TigerCS.Domain.Modules.IdentityAndAccess.Employee", null)
                        .WithMany()
                        .HasForeignKey("AssignedEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TigerCS.Domain.Modules.IdentityAndAccess.Employee", null)
                        .WithMany()
                        .HasForeignKey("AssigningActorEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TigerCS.Domain.Modules.Ticketing.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.Ticketing.TicketInteractionContext", b =>
                {
                    b.HasOne("TigerCS.Domain.Modules.Ticketing.Ticket", null)
                        .WithOne()
                        .HasForeignKey("TigerCS.Domain.Modules.Ticketing.TicketInteractionContext", "TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.Ticketing.TicketNote", b =>
                {
                    b.HasOne("TigerCS.Domain.Modules.IdentityAndAccess.Employee", null)
                        .WithMany()
                        .HasForeignKey("AuthorEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TigerCS.Domain.Modules.Ticketing.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.Ticketing.TicketPendingRecord", b =>
                {
                    b.HasOne("TigerCS.Domain.Modules.IdentityAndAccess.Employee", null)
                        .WithMany()
                        .HasForeignKey("ResumedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TigerCS.Domain.Modules.IdentityAndAccess.Employee", null)
                        .WithMany()
                        .HasForeignKey("StartedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TigerCS.Domain.Modules.Ticketing.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.Ticketing.TicketRequesterSnapshot", b =>
                {
                    b.HasOne("TigerCS.Domain.Modules.Ticketing.Ticket", null)
                        .WithOne()
                        .HasForeignKey("TigerCS.Domain.Modules.Ticketing.TicketRequesterSnapshot", "TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.Ticketing.TicketResolution", b =>
                {
                    b.HasOne("TigerCS.Domain.Modules.Ticketing.Ticket", null)
                        .WithMany()
                        .HasForeignKey("DuplicateOfTicketId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TigerCS.Domain.Modules.IdentityAndAccess.Employee", null)
                        .WithMany()
                        .HasForeignKey("ResolvingEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TigerCS.Domain.Modules.Ticketing.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.Ticketing.TicketStatusHistory", b =>
                {
                    b.HasOne("TigerCS.Domain.Modules.IdentityAndAccess.Employee", null)
                        .WithMany()
                        .HasForeignKey("ActorEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TigerCS.Domain.Modules.Ticketing.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.WorkflowConfiguration.DepartmentWorkflowSettings", b =>
                {
                    b.HasOne("TigerCS.Domain.Modules.IdentityAndAccess.Department", null)
                        .WithOne()
                        .HasForeignKey("TigerCS.Domain.Modules.WorkflowConfiguration.DepartmentWorkflowSettings", "DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.WorkflowConfiguration.RequestType", b =>
                {
                    b.HasOne("TigerCS.Domain.Modules.SlaAndEscalation.Priority", null)
                        .WithMany()
                        .HasForeignKey("DefaultPriorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TigerCS.Domain.Modules.IdentityAndAccess.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TigerCS.Domain.Modules.WorkflowConfiguration.WorkflowTemplate", null)
                        .WithMany()
                        .HasForeignKey("WorkflowTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.WorkflowConfiguration.RequestTypeAssignmentRule", b =>
                {
                    b.HasOne("TigerCS.Domain.Modules.IdentityAndAccess.Employee", null)
                        .WithMany()
                        .HasForeignKey("PrimaryEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TigerCS.Domain.Modules.WorkflowConfiguration.RequestType", null)
                        .WithOne()
                        .HasForeignKey("TigerCS.Domain.Modules.WorkflowConfiguration.RequestTypeAssignmentRule", "RequestTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.WorkflowConfiguration.RequestTypeAssignmentRuleMember", b =>
                {
                    b.HasOne("TigerCS.Domain.Modules.IdentityAndAccess.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TigerCS.Domain.Modules.WorkflowConfiguration.RequestTypeAssignmentRule", "Rule")
                        .WithMany("Members")
                        .HasForeignKey("RequestTypeAssignmentRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.WorkflowConfiguration.RequestTypeSlaPolicy", b =>
                {
                    b.HasOne("TigerCS.Domain.Modules.SlaAndEscalation.Priority", null)
                        .WithMany()
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TigerCS.Domain.Modules.WorkflowConfiguration.RequestType", null)
                        .WithMany()
                        .HasForeignKey("RequestTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.WorkflowConfiguration.WorkflowTemplateStep", b =>
                {
                    b.HasOne("TigerCS.Domain.Modules.WorkflowConfiguration.WorkflowTemplate", "WorkflowTemplate")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowTemplate");
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.CustomerVerification.UnitReference", b =>
                {
                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.IdentityAndAccess.Employee", b =>
                {
                    b.Navigation("DepartmentAssignments");
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.WorkflowConfiguration.RequestTypeAssignmentRule", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("TigerCS.Domain.Modules.WorkflowConfiguration.WorkflowTemplate", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
